### ISSUE TITLE
One-tailed hypothesis test

### ISSUE THREAD

**Issue by CorentinWicht** [arcaldwell49/Superpower#15]
Dear developers,

many thanks for your impressive package.
I have been using it recently to estimate the sample size required to reach 90% with a 5% for a Registered Report.

I have a 2 groups between-subjects design and hold a strong hypothesis regarding the direction of the expected effect (Group 1 < Group 2). 

How can I use the ANOVA_design or the ANOVA_power function to simulate **one-tailed hypothesis tests**? 
From what I see it seems impossible, do you have any suggestion (since this will considerably change the required N)?

Best,

Corentin

**Comment by Lakens** [comment]
Hi, 
you just double the alpha level. If you have a one-sided test at 5%, you would enter an alpha level of .10.
Best,
Daniel
