### ISSUE TITLE
minor documents

### ISSUE THREAD

**Issue by tbates** [arcaldwell49/Superpower#29]
Great package! couple of v.minor doc things I noted learning the package:

1. The super icon displays ginormously in CRAN's [readme view](https://cran.r-project.org/web/packages/Superpower/readme/README.html). Perhaps upload a smaller one?
1. In the NEWS you suggest people to `?design_aov-methods` but this gives:
> Error in eval(argExpr, envir) : object 'design_aov' not found
Error in .signatureFromCall(fdef, expr, envir, doEval) : 
  error in trying to evaluate the expression for argument ‘e1’ (design_aov)

Perhaps just say `methods(class="design_aov")` which yields the expected treasure:
> [1] plot  print
see '?methods' for accessing help and source code

**Comment by arcaldwell49** [comment]
Okay, the readme is updated. Working on the "NEWS" fix

**Comment by arcaldwell49** [comment]
@tbates can you provide me with which version of Superpower you are working with? If Superpower is loaded (i.e., library(Superpower) ?`design_aov-methods` provides the right response.

**Comment by arcaldwell49** [comment]
Crud, figured it out. I needed escape characters around that line
Try:

 ?\`design_aov-methods\`

**Comment by tbates** [comment]
devtools version
packageVersion("Superpower")
[1] ‘0.1.2’

R version: R version 4.1.1 (2021-08-10)
MacOS: 12.0.1

library("Superpower")
> ?design_aov-methods
Error in eval(argExpr, envir) : object 'design_aov' not found
Error in .signatureFromCall(fdef, expr, envir, doEval) : 
  error in trying to evaluate the expression for argument ‘e1’ (design_aov)

**Comment by tbates** [comment]
it's so minor I felt ashamed noting it.

**Comment by arcaldwell49** [comment]
Lol, it's all good. 

Advanced users, like yourself, would be fine but this would cause a lot of confusion for beginners.

Small problem and an easy fix. Going to close this one
