### ISSUE TITLE
typo in code

### ISSUE THREAD

**Issue by Pete-Nelson** [arcaldwell49/Superpower#32]
Minor detail but errors, corrected below, prevent example code from working: In Chapter 6, 

`simulation_result <- ANOVA_power(design_result, 
                                 alpha_level = alpha, # '= alpha_level' previously
                                 nsims = nSims, # '= nsims' previously
                                 verbose = FALSE)`
and 
`exact_result <- ANOVA_exact(design_result,
                            alpha_level = alpha, # '= alpha_level' previously
                            verbose = FALSE)`

Since I'm here, the intro is great. I'd love to see a really practical discussion of designing a pilot experiment to provide those
starting means and sd. Thanks!

**Comment by arcaldwell49** [comment]
Hi there, great catch but this is the repo for the package itself not the book https://github.com/arcaldwell49/SuperpowerBook
