### ISSUE TITLE
Blank Output Running Superpower in R 4.1.2

### ISSUE THREAD

**Issue by PRussRich** [arcaldwell49/Superpower#33]
I really appreciate the work you all have done with the package and the Shiny app. I have used the app to get a preliminary power analysis for an upcoming study I'm conducting. But, I was hoping to conduct the power analysis in R so that I can have the relevant file on hand and easily adapt the file for future studies. When I try to run the power analyses in R though the output is entirely blank except for some strings that are meant to guide the user when reading the output. I've tried using some of the example code from both your _Advances in Methods_ paper and from the Superpower book, but have the same issues. 

> string <- "2b"
n <- 100
mu <- c(24, 26.2)
sd <- 6.4
labelnames <- c("condition", "control", "pet") 
design_result <- ANOVA_design(design = string,
                   n = n,
                   mu = mu,
                   sd = sd,
                   labelnames = labelnames)
alpha_level <- 0.05
exact_result <- ANOVA_exact(design_result,
                            alpha_level = alpha_level,
                            verbose = FALSE)
exact_result

When I run the above code I receive the following ouput (I've removed some of the lines of code above from the output just for brevity):

> exact_result
Power and Effect sizes for ANOVA tests
Power and Effect sizes for pairwise comparisons (t-tests)

I've made sure to install the Superpower package and load the Superpower library, so I'm not entirely sure what the issue is. Is it possible there's a package I need to have loaded that I don't have installed or loaded which isn't being flagged when I load Superpower?

Thanks for the help and please let me know if you need any further information from me!

**Comment by Lakens** [comment]
Hi, can you report the full output, without brevity? There is not enough information to see what the problem is. You are either getting the output on a location you are not expection (e.g., using an R notebook) or you are missing a dependency because you did not use the default way to install the package, I am guessing.

**Comment by PRussRich** [comment]
Thanks! Your note about the output showing up in an unexpected location appears to be the issue. Something with how RMarkdown was interacting with my code segment was leading the output figures and tables to not show up in the RMarkdown file itself or in the R Console. Thanks for pointing me in the right direction!
