### ISSUE TITLE
effect sizes in mixed ANOVA

### ISSUE THREAD

**Issue by ballarinit** [arcaldwell49/Superpower#34]
Hi and thanks for this great tool. 

I was reading the online manual associated with it (https://aaroncaldwell.us/SuperpowerBook/mixed-anova.html).
Under section '5. mixed ANOVA', I see that there are some comparisons between G*Power and Superpower. 
In the very first example in section 5.1 the G*Power calculation is based on an effect size f=0.25, while in the table 5.2 the output of the simulation-based analysis reports Cohen f=0.51.
I thought these numbers should have been the same here. Am I missing something?
 
My goal is to run a simulation for the sample size definition with 2w*2b design. 

Thank you, 

Tommaso

**Comment by arcaldwell49** [comment]
Hi, a new version is online. The problem was with the screenshot. Please note, issues with the book should be raised on the book's repository https://github.com/arcaldwell49/SuperpowerBook/issue
