### ISSUE TITLE
Three-way interaction for multiple regression?

### ISSUE THREAD

**Issue by rempsyc** [arcaldwell49/Superpower#35]
Reading the [documentation ](https://aaroncaldwell.us/SuperpowerBook/power-for-three-way-interactions.html) led me to believe that it is not possible to do a power analysis for a three-way interaction with `Superpower` (for multiple regression, not ANOVA). I would just like to verify that this is correct? I have two binary variables (experimental manipulations) and one continuous variable. If three-way interactions are not supported at this time, are you expecting to add support in the future?

Would you recommend for now using custom simulations as described in the book ([Ch. 15](https://aaroncaldwell.us/SuperpowerBook/beyond-superpower-ii-custom-simulations.html))? Thanks.

Not sure if related to #3.

**Comment by arcaldwell49** [comment]
Correct. There is no work in progress to add this as a feature, though the package does now support ANCOVA (which I suspect may be more appropriate unless the continuous variable is also experimentally manipulated.

A custom simulation is your best shot if you want to include the 3-way interaction. You'd need to generate 2 correlated variables (dependent variable and covariate, assuming the covariate isn't experimentally assigned). Then you would randomly assign subjects to 1 of the 2 experimental conditions within the simulation.
