### ISSUE TITLE
Error downloading PDF

### ISSUE THREAD

**Issue by btoizer** [arcaldwell49/Superpower#40]
Hi, thanks for making such a user-friendly power analysis app!!

I am having problems downloading the PDF report after running a power analysis using the ANOVA_power app. When I click on the Download PDF Report button, it tries to download a file called "report.html" but I get a "Failed - Server problem" error. The button goes to the url: https://shiny.ieis.tue.nl/anova_power/session/3980de5f7d4895f95f44623b8980e00c/download/report?w=

**Comment by Lakens** [comment]
Hi, that app might not have been updated in a while. The main up to date app is at https://arcaldwell49.shinyapps.io/anova-exact/ Can you give that a try?

**Comment by btoizer** [comment]
You're right, I can download the PDF using that URL. Thanks!
