### ISSUE TITLE
Error in eigen(qr.coef(if (repeated) qr(x$SSPE[[term]]) else SSPE.qr,  :    infinite or missing values in 'x'

### ISSUE THREAD

**Issue by galambda** [arcaldwell49/Superpower#41]
Hi all,

I've encountered the above error when trying to run ANOVA_power based on the following design:

design_result <- ANOVA_design(design = "2w*2b", n = 30, 
                              mu = c(-0.25,0.25,0.25,-0.25), sd = 1,r = 0.5, 
  labelnames = c("time", "pre", "post", "branch", "Psil+Pim", "Psil+Plac")
)

sim_result <- ANOVA_power(design_result,
                          alpha_level = 0.05, 
                          p_adjust = "none",
                          nsims = 1000)

Error in eigen(qr.coef(if (repeated) qr(x$SSPE[[term]]) else SSPE.qr,  : 
  infinite or missing values in 'x'

Please advise.

Thanks,
Philipp

**Comment by arcaldwell49** [comment]
labelnames cannot contain symbols.

The code runs fine without the + sign

```
design_result <- ANOVA_design(design = "2w*2b", n = 30,
                              mu = c(-0.25,0.25,0.25,-0.25), sd = 1,
                              r = 0.5 ,
                              labelnames = c("time", "pre", "post", "branch", "PsilPim", "PsilPlac")
)

sim_result <- ANOVA_power(design_result,
                          alpha_level = 0.05,
                          p_adjust = "none",
                          nsims = 1000)
```
